import type { Content } from '../types';

export const mockContent: Content[] = [
  {
    id: '1',
    title: 'Городской пейзаж на закате',
    description: 'Панорамный вид современного города во время золотого часа',
    tags: ['город', 'закат', 'пейзаж', 'архитектура', 'skyline'],
    category: 'architecture',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400',
    author: { id: '1', name: 'Алексей Петров', email: '', role: 'author', credits: 0, plan: 'pro', createdAt: '' },
    downloads: 1247,
    likes: 89,
    credits: 5,
    resolution: '4000x2667',
    format: 'JPEG',
    fileSize: '12.4 MB',
    createdAt: '2026-01-15',
  },
  {
    id: '2',
    title: 'Технологический абстрактный фон',
    description: 'Минималистичный градиентный фон для презентаций и постов',
    tags: ['абстракция', 'технологии', 'фон', 'градиент', 'минимализм'],
    category: 'abstract',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1557683316-973673baf926?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1557683316-973673baf926?w=400',
    author: { id: '2', name: 'Мария Иванова', email: '', role: 'author', credits: 0, plan: 'pro', createdAt: '' },
    downloads: 3421,
    likes: 234,
    credits: 3,
    resolution: '3840x2160',
    format: 'PNG',
    fileSize: '8.2 MB',
    createdAt: '2026-02-10',
  },
  {
    id: '3',
    title: 'Деловая встреча в офисе',
    description: 'Современный коворкинг с командой профессионалов',
    tags: ['бизнес', 'офис', 'команда', 'встреча', 'работа'],
    category: 'business',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400',
    author: { id: '3', name: 'Дмитрий Козлов', email: '', role: 'author', credits: 0, plan: 'starter', createdAt: '' },
    downloads: 892,
    likes: 67,
    credits: 5,
    resolution: '5472x3648',
    format: 'JPEG',
    fileSize: '15.7 MB',
    createdAt: '2026-03-05',
  },
  {
    id: '4',
    title: 'Ноутбук и кофе на столе',
    description: 'Рабочее место фрилансера — ноутбук, кофе и записная книжка',
    tags: ['ноутбук', 'кофе', 'фриланс', 'workspace', 'минимализм'],
    category: 'technology',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400',
    author: { id: '1', name: 'Алексей Петров', email: '', role: 'author', credits: 0, plan: 'pro', createdAt: '' },
    downloads: 2156,
    likes: 178,
    credits: 3,
    resolution: '4000x2667',
    format: 'JPEG',
    fileSize: '9.8 MB',
    createdAt: '2026-02-20',
  },
  {
    id: '5',
    title: 'Свежие фрукты на дереве',
    description: 'Яркое фото спелых фруктов в естественном освещении',
    tags: ['фрукты', 'еда', 'природа', 'organic', 'яркий'],
    category: 'food',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?w=400',
    author: { id: '4', name: 'Елена Сидорова', email: '', role: 'author', credits: 0, plan: 'starter', createdAt: '' },
    downloads: 567,
    likes: 45,
    credits: 4,
    resolution: '3000x2000',
    format: 'JPEG',
    fileSize: '7.3 MB',
    createdAt: '2026-04-01',
  },
  {
    id: '6',
    title: 'Путешествие в горы',
    description: 'Величественные горы в утренней дымке',
    tags: ['горы', 'путешествие', 'природа', 'пейзаж', 'adventure'],
    category: 'travel',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400',
    author: { id: '2', name: 'Мария Иванова', email: '', role: 'author', credits: 0, plan: 'pro', createdAt: '' },
    downloads: 1893,
    likes: 156,
    credits: 5,
    resolution: '5184x3456',
    format: 'JPEG',
    fileSize: '14.2 MB',
    createdAt: '2026-01-28',
  },
  {
    id: '7',
    title: 'Модная фотосессия',
    description: 'Стильный портрет в студийном освещении',
    tags: ['мода', 'портрет', 'стиль', 'studio', 'fashion'],
    category: 'fashion',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400',
    author: { id: '3', name: 'Дмитрий Козлов', email: '', role: 'author', credits: 0, plan: 'starter', createdAt: '' },
    downloads: 734,
    likes: 92,
    credits: 6,
    resolution: '4000x6000',
    format: 'JPEG',
    fileSize: '11.5 MB',
    createdAt: '2026-03-15',
  },
  {
    id: '8',
    title: 'Стеклянное здание внизу',
    description: 'Современная архитектура с отражениями в стекле',
    tags: ['архитектура', 'здание', 'стекло', 'город', 'современность'],
    category: 'architecture',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=400',
    author: { id: '4', name: 'Елена Сидорова', email: '', role: 'author', credits: 0, plan: 'starter', createdAt: '' },
    downloads: 1102,
    likes: 81,
    credits: 4,
    resolution: '4500x3000',
    format: 'JPEG',
    fileSize: '10.9 MB',
    createdAt: '2026-02-12',
  },
  {
    id: '9',
    title: 'Нейронная сеть визуализация',
    description: 'Абстрактная 3D-визуализация нейронных связей',
    tags: ['AI', 'нейросеть', 'технологии', '3D', 'абстракция'],
    category: 'technology',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400',
    author: { id: '1', name: 'Алексей Петров', email: '', role: 'author', credits: 0, plan: 'pro', createdAt: '' },
    downloads: 4521,
    likes: 312,
    credits: 7,
    resolution: '3840x2160',
    format: 'PNG',
    fileSize: '18.4 MB',
    createdAt: '2026-04-10',
  },
  {
    id: '10',
    title: 'Зелёный мох крупным планом',
    description: 'Макрофото текстуры мха — идеально для фонов',
    tags: ['природа', 'мох', 'текстура', 'макро', 'зелёный'],
    category: 'nature',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=400',
    author: { id: '2', name: 'Мария Иванова', email: '', role: 'author', credits: 0, plan: 'pro', createdAt: '' },
    downloads: 678,
    likes: 54,
    credits: 3,
    resolution: '4000x3000',
    format: 'JPEG',
    fileSize: '8.7 MB',
    createdAt: '2026-03-22',
  },
  {
    id: '11',
    title: 'Мокет буклета на столе',
    description: 'Реалистичный мокет рекламного буклета в интерьере',
    tags: ['мокет', 'дизайн', 'презентация', 'branding', 'плоский'],
    category: 'mockups',
    type: 'photo',
    url: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=400',
    author: { id: '3', name: 'Дмитрий Козлов', email: '', role: 'author', credits: 0, plan: 'starter', createdAt: '' },
    downloads: 2340,
    likes: 189,
    credits: 5,
    resolution: '5000x3333',
    format: 'PSD',
    fileSize: '24.1 MB',
    createdAt: '2026-01-05',
  },
  {
    id: '12',
    title: 'Минималистичная бизнес-презентация',
    description: 'Шаблон слайда для деловой презентации в минималистичном стиле',
    tags: ['шаблон', 'презентация', 'бизнес', 'минимализм', 'slide'],
    category: 'templates',
    type: 'template',
    url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400',
    author: { id: '4', name: 'Елена Сидорова', email: '', role: 'author', credits: 0, plan: 'starter', createdAt: '' },
    downloads: 1567,
    likes: 123,
    credits: 8,
    resolution: '1920x1080',
    format: 'PPTX',
    fileSize: '5.6 MB',
    createdAt: '2026-04-05',
  },
];

export const aiModels = [
  { id: 'flux', name: 'Flux Pro', description: 'Высокое качество, детализация', credits: 3, type: 'photo' as const },
  { id: 'sdxl', name: 'Stable Diffusion XL', description: 'Быстрая генерация, стили', credits: 2, type: 'photo' as const },
  { id: 'dalle', name: 'DALL-E 3', description: 'Креативность, точность', credits: 5, type: 'photo' as const },
  { id: 'midjourney', name: 'Midjourney v6', description: 'Художественность', credits: 5, type: 'photo' as const },
  { id: 'kling', name: 'Kling AI', description: 'Видео до 10 сек', credits: 10, type: 'video' as const },
  { id: 'runway', name: 'Runway Gen-3', description: 'Движение камеры', credits: 12, type: 'video' as const },
  { id: 'pika', name: 'Pika Labs', description: 'Короткие клипы', credits: 8, type: 'video' as const },
];

export const categories = [
  { id: 'all', name: 'Все', icon: 'grid' },
  { id: 'business', name: 'Бизнес', icon: 'briefcase' },
  { id: 'technology', name: 'Технологии', icon: 'cpu' },
  { id: 'nature', name: 'Природа', icon: 'leaf' },
  { id: 'people', name: 'Люди', icon: 'users' },
  { id: 'food', name: 'Еда', icon: 'utensils' },
  { id: 'travel', name: 'Путешествия', icon: 'map-pin' },
  { id: 'fashion', name: 'Мода', icon: 'shirt' },
  { id: 'architecture', name: 'Архитектура', icon: 'building' },
  { id: 'abstract', name: 'Абстракция', icon: 'sparkles' },
  { id: 'templates', name: 'Шаблоны', icon: 'layout' },
  { id: 'mockups', name: 'Мокеты', icon: 'image' },
];
